# Generated by Django 6.0.6 on 2026-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_data_entry',
            field=models.BooleanField(db_index=True, default=False, help_text='True for bootstrap opening-balance / opening-stock orders. Hidden from normal list views.'),
        ),
    ]
