# Generated by Django 6.0.6 on 2026-07-16 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseorder_is_data_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostInventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated e.g. LOSS-2026-0001', max_length=30, unique=True)),
                ('note', models.TextField(blank=True, default='', help_text='Optional overall note for this batch.')),
                ('total_lost_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost Inventory Record',
                'verbose_name_plural': 'Lost Inventory Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', help_text='Optional reason e.g. damaged, expired, stolen, misplaced.', max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_items', to='purchases.product')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.lostinventoryrecord')),
            ],
            options={
                'verbose_name': 'Lost Inventory Item',
                'verbose_name_plural': 'Lost Inventory Items',
                'unique_together': {('record', 'product')},
            },
        ),
    ]
