# Generated by Django 6.0.6 on 2026-07-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_lostinventoryrecord_lostinventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostinventoryrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
    ]
