# Generated by Django 6.0.6 on 2026-07-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_lostinventoryrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostinventoryitem',
            name='found_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LostInventoryFIFOConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity originally drawn from this batch when marked lost.')),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Tax-inclusive unit cost of this batch at the time of loss.', max_digits=14)),
                ('restored_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifo_consumptions', to='purchases.lostinventoryitem')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_inventory_consumptions', to='purchases.purchaseitem')),
            ],
            options={
                'verbose_name': 'Lost Inventory FIFO Consumption',
                'verbose_name_plural': 'Lost Inventory FIFO Consumptions',
                'ordering': ['id'],
            },
        ),
    ]
