# Generated by Django 6.0.6 on 2026-07-28 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_lostinventoryitem_found_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchased', models.PositiveIntegerField(default=0)),
                ('total_purchase_returned', models.PositiveIntegerField(default=0)),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_sale_returned', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Movement Flow',
                'verbose_name_plural': 'Stock Movement Flow',
            },
        ),
        migrations.CreateModel(
            name='ProductStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchased', models.PositiveIntegerField(default=0)),
                ('total_purchase_returned', models.PositiveIntegerField(default=0)),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_sale_returned', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='purchases.product')),
            ],
            options={
                'verbose_name': 'Product Stock Movement',
                'verbose_name_plural': 'Product Stock Movement',
            },
        ),
    ]
