# Generated by Django 6.0.6 on 2026-07-28 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_stockmovementflow_productstockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostInventoryRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('recovered_amount', models.DecimalField(decimal_places=4, editable=False, max_digits=18)),
                ('recovered_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='purchases.lostinventoryitem')),
                ('recovered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_inventory_recoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost Inventory Recovery',
                'verbose_name_plural': 'Lost Inventory Recoveries',
                'ordering': ['-recovered_at', '-id'],
            },
        ),
    ]
