# Generated by Django 6.0.6 on 2026-07-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_lostinventoryrecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockmovement',
            name='total_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstockmovement',
            name='total_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovementflow',
            name='total_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovementflow',
            name='total_lost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
