# Generated by Django 6.0.6 on 2026-08-09 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_trigram_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shelf',
        ),
        migrations.CreateModel(
            name='PurchaseItemShelfAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='purchases.purchaseitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_item_allocations', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Purchase Item Shelf Allocation',
                'verbose_name_plural': 'Purchase Item Shelf Allocations',
                'unique_together': {('purchase_item', 'shelf')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItemShelfAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='purchases.purchasereturnitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_item_allocations', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Purchase Return Item Shelf Allocation',
                'verbose_name_plural': 'Purchase Return Item Shelf Allocations',
                'unique_together': {('return_item', 'shelf')},
            },
        ),
        migrations.CreateModel(
            name='ShelfStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_stock_rows', to='purchases.product')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_rows', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Shelf Stock',
                'verbose_name_plural': 'Shelf Stock',
                'unique_together': {('shelf', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ShelfStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = added to shelf, negative = removed from shelf.')),
                ('reason', models.CharField(choices=[('purchase_putaway', 'Purchase Put-Away'), ('sale_consumption', 'Sale Consumption'), ('invoice_return_putaway', 'Invoice Return Put-Away'), ('purchase_return_consumption', 'Purchase Return Consumption'), ('lost_consumption', 'Lost Inventory Consumption'), ('lost_found_putaway', 'Lost Inventory Found Put-Away'), ('move_out', 'Manual Move (Out)'), ('move_in', 'Manual Move (In)'), ('backfill', 'Backfill')], db_index=True, max_length=30)),
                ('reference', models.CharField(blank=True, default='', help_text='e.g. PO-2026-0001, BILL-2026-0001', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf_movements', to='purchases.product')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Shelf Stock Movement',
                'verbose_name_plural': 'Shelf Stock Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shelf', '-created_at'], name='purchases_s_shelf_i_4cb46b_idx'), models.Index(fields=['product', '-created_at'], name='purchases_s_product_5fc577_idx')],
            },
        ),
    ]
