# Generated by Django 6.0.6 on 2026-09-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_alter_supplierpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='avg_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
