# Generated by Django 6.0.6 on 2026-07-25 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('valuation_method', models.CharField(choices=[('depreciation', 'Depreciation'), ('revaluation', 'Revaluation'), ('none', 'None (never changes)')], max_length=12)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=0, help_text="Annual reducing-balance rate (e.g. 0.15 for 15%). Only meaningful when valuation_method is 'depreciation'. Editable any time — only affects entries posted after the change.", max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acquisition_type', models.CharField(choices=[('existing', 'Existing'), ('new', 'New')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('acquisition_date', models.DateField(db_index=True)),
                ('current_worth', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
                ('is_disposed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-acquisition_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_type', models.CharField(choices=[('scrapped', 'Scrapped'), ('sold', 'Sold')], max_length=10)),
                ('disposal_date', models.DateField(db_index=True)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('worth_at_disposal', models.DecimalField(decimal_places=4, help_text="Asset's current_worth snapshotted at the moment of disposal.", max_digits=18)),
                ('gain_loss', models.DecimalField(blank=True, decimal_places=4, help_text='sale_amount - worth_at_disposal. Null for scrapped assets.', max_digits=18, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'ordering': ['-disposal_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_asset_cost', models.DecimalField(decimal_places=4, default=0, help_text='Sum of cost across all active (non-disposed) assets.', max_digits=20)),
                ('total_current_worth', models.DecimalField(decimal_places=4, default=0, help_text='Sum of current_worth across all active (non-disposed) assets.', max_digits=20)),
                ('total_accumulated_depreciation', models.DecimalField(decimal_places=4, default=0, help_text='total_asset_cost - total_current_worth, for depreciation-method assets only.', max_digits=20)),
                ('total_disposed_count', models.PositiveIntegerField(default=0)),
                ('total_gain_on_disposal', models.DecimalField(decimal_places=4, default=0, help_text='Sum of positive gain_loss across all sold disposals (gross).', max_digits=20)),
                ('total_loss_on_disposal', models.DecimalField(decimal_places=4, default=0, help_text='Sum of absolute negative gain_loss across all sold disposals (gross).', max_digits=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_flow_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Flow',
                'verbose_name_plural': 'Asset Flow',
            },
        ),
        migrations.CreateModel(
            name='AssetValuationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('depreciation', 'Depreciation'), ('revaluation', 'Revaluation')], max_length=12)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM this entry applies to.', max_length=7)),
                ('rate_applied', models.DecimalField(blank=True, decimal_places=4, help_text='Depreciation rate used for this entry. Null for revaluations.', max_digits=5, null=True)),
                ('worth_before', models.DecimalField(decimal_places=4, max_digits=18)),
                ('worth_after', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, help_text='worth_after - worth_before. Negative for depreciation, either sign for revaluation.', max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_entries', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_valuation_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Valuation Entry',
                'verbose_name_plural': 'Asset Valuation Entries',
                'ordering': ['-period', '-created_at'],
                'indexes': [models.Index(fields=['asset', 'entry_type', '-period'], name='idx_asset_valuation_lookup')],
            },
        ),
    ]
