# Generated by Django 6.0.6 on 2026-08-04 03:39

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def repair_duplicate_depreciation(apps, schema_editor):
    """
    The concurrent-catch-up race this migration's constraint closes has
    ALREADY produced duplicate (asset, period) depreciation rows in real
    databases (found in dev on 2026-08-04) — each duplicate double-deducted
    the asset's worth. Repair before the constraint can be added:
      1. keep only the earliest depreciation entry per (asset, period);
      2. recompute each affected asset's current_worth = cost + sum of its
         remaining entry amounts (amounts are signed: depreciation negative,
         revaluation either sign — so this reproduces the intended history);
      3. rebuild AssetFlow's cost/worth/accumulated totals from the repaired
         assets (disposal totals are unaffected by this bug).
    """
    AssetValuationEntry = apps.get_model("assets", "AssetValuationEntry")
    Asset = apps.get_model("assets", "Asset")
    AssetFlow = apps.get_model("assets", "AssetFlow")

    seen = {}
    dupe_ids, affected_asset_ids = [], set()
    entries = AssetValuationEntry.objects.filter(entry_type="depreciation").order_by(
        "asset_id", "period", "id",
    ).values_list("id", "asset_id", "period")
    for entry_id, asset_id, period in entries:
        key = (asset_id, period)
        if key in seen:
            dupe_ids.append(entry_id)
            affected_asset_ids.add(asset_id)
        else:
            seen[key] = entry_id

    if not dupe_ids:
        return

    AssetValuationEntry.objects.filter(id__in=dupe_ids).delete()

    for asset in Asset.objects.filter(id__in=affected_asset_ids):
        total_amount = Decimal("0")
        for (amount,) in AssetValuationEntry.objects.filter(asset=asset).values_list("amount"):
            total_amount += amount
        asset.current_worth = asset.cost + total_amount
        asset.save(update_fields=["current_worth"])

    flow = AssetFlow.objects.filter(pk=1).first()
    if flow is not None:
        active = Asset.objects.filter(is_deleted=False, is_disposed=False).select_related("category")
        flow.total_asset_cost = sum((a.cost for a in active), Decimal("0"))
        flow.total_current_worth = sum((a.current_worth for a in active), Decimal("0"))
        flow.total_accumulated_depreciation = sum(
            (a.cost - a.current_worth for a in active
             if a.category.valuation_method == "depreciation"),
            Decimal("0"),
        )
        flow.save(update_fields=[
            "total_asset_cost", "total_current_worth", "total_accumulated_depreciation",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(repair_duplicate_depreciation, migrations.RunPython.noop),
        migrations.AddField(
            model_name='assetflow',
            name='depreciation_caught_up_through',
            field=models.CharField(blank=True, default='', help_text="YYYY-MM through which EVERY active asset's depreciation is posted. Depreciation only becomes due at month boundaries, so while this equals the current month the per-asset catch-up loop can be skipped entirely (O(1) staleness check — same pattern as CashManagementFlow.growth_caught_up_through). Reset to '' by update_asset_category on a rate change so the new rate takes effect on the very next read.", max_length=7),
        ),
        migrations.AddConstraint(
            model_name='assetvaluationentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'depreciation')), fields=('asset', 'period'), name='uniq_asset_depreciation_period'),
        ),
    ]
