# Generated by Django 6.0.6 on 2026-07-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_is_data_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
