# Generated by Django 6.0.6 on 2026-08-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_trigram_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount received in advance (only when payment_type=advance). Immediately added to cash_in_hand on draft creation. Capped at grand_total on confirmation.', max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance Payment'), ('after_delivery', 'Payment After Delivery')], default='after_delivery', help_text='Advance payment or payment after delivery.', max_length=20),
        ),
    ]
