# Generated by Django 6.0.6 on 2026-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_advance_amount_invoice_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Set by the user at invoice creation (defaults to +7 days if omitted). Carried through unchanged at confirmation. Editable at any time, including after confirmation, via the dedicated due-date endpoint.', null=True),
        ),
    ]
