# Generated by Django 6.0.6 on 2026-08-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_payment_due_date'),
        ('purchases', '0012_remove_product_shelf_purchaseitemshelfallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemShelfAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='billing.invoiceitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item_allocations', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Invoice Item Shelf Allocation',
                'verbose_name_plural': 'Invoice Item Shelf Allocations',
                'unique_together': {('invoice_item', 'shelf')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceReturnItemShelfAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_allocations', to='billing.returnitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_return_item_allocations', to='purchases.shelf')),
            ],
            options={
                'verbose_name': 'Invoice Return Item Shelf Allocation',
                'verbose_name_plural': 'Invoice Return Item Shelf Allocations',
                'unique_together': {('return_item', 'shelf')},
            },
        ),
    ]
