# Generated by Django 6.0.6 on 2026-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_outstanding_index_include_data_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('bank', 'Bank Transfer'), ('multiple', 'Multiple Methods')], help_text='Derived display label — see payment_methods.PaymentAllocation for the real split.', max_length=100),
        ),
    ]
