# Generated by Django 6.0.6 on 2026-09-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_fifoledger_reverses'),
        ('sales_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code_suffix',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='sales_man.salesman'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_man_link_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='sales_man.salesmanlinkname'),
        ),
    ]
