# Generated by Django 6.0.6 on 2026-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7, unique=True)),
                ('cash_in_hand', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('accounts_receivable', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('inventory_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fixed_assets_nbv', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_assets', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('accounts_payable', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gst_payable', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('wht_payable', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_liabilities', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('owner_capital', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('investor_capital', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('retained_earnings', models.DecimalField(decimal_places=4, default=0, help_text='Cumulative net profit minus everything already paid out or reinvested.', max_digits=20)),
                ('total_equity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Balance Sheet Snapshot',
                'verbose_name_plural': 'Balance Sheet Snapshots',
                'ordering': ['-period'],
            },
        ),
    ]
