# Generated by Django 6.0.6 on 2026-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetsnapshot',
            name='opening_balance_equity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Net offset for go-live bootstrap data (data_entry app): +customer opening balances, +opening stock, -supplier opening balances. Each of those creates an asset or liability with no natural double-entry counterpart, so without this line the balance sheet would never balance for a business that used the Data Entry app to bootstrap pre-existing debts/stock at go-live.', max_digits=20),
        ),
    ]
