# Generated by Django 6.0.6 on 2026-08-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_balancesheetsnapshot_opening_balance_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetsnapshot',
            name='asset_revaluation_surplus',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Net of all AssetValuationEntry REVALUATION amounts (signed, so downward revaluations reduce it). Only DEPRECIATION entries feed net profit, so a revaluation moves current_worth with nothing on the other side — this is the standard revaluation-surplus offset.', max_digits=20),
        ),
        migrations.AddField(
            model_name='balancesheetsnapshot',
            name='pre_owned_asset_equity',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Total cost of assets registered with acquisition_type='existing' (already owned before being recorded, so no cash ever left the business). Like opening stock, these add an asset with no natural counterpart — without this line the sheet cannot balance for any business that registered a pre-owned asset. Includes disposed ones: removing them would strand the depreciation already expensed through retained earnings.", max_digits=20),
        ),
    ]
