# Generated by Django 6.0.6 on 2026-08-12 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStatsFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('total_creates', models.PositiveIntegerField(default=0)),
                ('total_updates', models.PositiveIntegerField(default=0)),
                ('total_deletes', models.PositiveIntegerField(default=0)),
                ('total_state_changes', models.PositiveIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Activity Stats Flow',
                'verbose_name_plural': 'Activity Stats Flow',
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('state_change', 'State Change')], db_index=True, max_length=20)),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_c86318_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_6e9aaf_idx'), models.Index(fields=['app_label', 'model_name', '-created_at'], name='activity_lo_app_lab_22fa8a_idx')],
            },
        ),
    ]
