# Generated by Django 6.0.6 on 2026-10-06 03:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0017_inventory_avg_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('request_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Not accepted'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=30)),
                ('import_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_purchase_request', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wht', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accepted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchases.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='b2b.purchaserequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='b2b.purchaserequestitem')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchases.shelf')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(condition=models.Q(('status', 'pending'), models.Q(('order__isnull', True), ('status', 'accepted')), _connector='OR'), fields=['created_at', 'id'], name='b2b_my_req_outstanding_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(fields=('provider_name', 'request_uuid'), name='b2b_my_request_uuid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='b2b_my_request_item_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestshelf',
            constraint=models.UniqueConstraint(fields=('item', 'shelf'), name='b2b_my_request_shelf_uniq'),
        ),
    ]
