# Generated by Django 6.0.6 on 2026-07-24 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_input_tax_paid', models.DecimalField(decimal_places=4, default=0, help_text='GST paid to suppliers, all-time (gross, only ever increases). This is money already spent — legally deductible from what you owe FBR.', max_digits=20)),
                ('total_output_tax_collected', models.DecimalField(decimal_places=4, default=0, help_text="GST charged to customers, all-time (gross, only ever increases). This is money you're holding on FBR's behalf, not yours to keep.", max_digits=20)),
                ('net_sales_tax_payable', models.DecimalField(decimal_places=4, default=0, help_text="output_tax_collected - input_tax_paid. What you'd owe FBR if registered and filing today. Stored field, recalculated on every sync.", max_digits=20)),
                ('total_sales_tax_paid', models.DecimalField(decimal_places=4, default=0, help_text='Actual GST payments made (via TaxPayment records), all-time (gross, only ever increases).', max_digits=20)),
                ('sales_tax_outstanding', models.DecimalField(decimal_places=4, default=0, help_text="net_sales_tax_payable - total_sales_tax_paid, floored at 0. What's left to pay right now.", max_digits=20)),
                ('total_wht_withheld_from_suppliers', models.DecimalField(decimal_places=4, default=0, help_text='Tax you deducted from supplier payments, all-time. Real cash you owe FBR, but not payment-tracked here in v1 — informational only.', max_digits=20)),
                ('total_wht_withheld_by_customers', models.DecimalField(decimal_places=4, default=0, help_text="Tax customers deducted from what they paid you, all-time. You never touch this money — it's a credit for your own annual return.", max_digits=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxflow_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Flow',
                'verbose_name_plural': 'Tax Flow',
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payment_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_payments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_payments_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_payments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Payment',
                'verbose_name_plural': 'Tax Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
