# Generated by Django 6.0.6 on 2026-07-26 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxflow',
            name='total_wht_paid',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Actual WHT deposits made to FBR (via WHTPayment records) against tax withheld from suppliers, all-time (gross, only ever increases).', max_digits=20),
        ),
        migrations.AddField(
            model_name='taxflow',
            name='wht_outstanding',
            field=models.DecimalField(decimal_places=4, default=0, help_text="total_wht_withheld_from_suppliers - total_wht_paid, floored at 0. What's still owed to FBR from tax already withheld from suppliers. Never netted against total_wht_withheld_by_customers — see docstring above.", max_digits=20),
        ),
        migrations.AlterField(
            model_name='taxflow',
            name='total_wht_withheld_by_customers',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Tax customers deducted from what they paid you, all-time. You never touch this money — it's a credit for your own annual return. Never netted against total_wht_withheld_from_suppliers — different taxpayer's obligation, informational only.", max_digits=20),
        ),
        migrations.AlterField(
            model_name='taxflow',
            name='total_wht_withheld_from_suppliers',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tax you deducted from supplier payments, all-time. Real cash you owe FBR — a liability, now payment-tracked via WHTPayment.', max_digits=20),
        ),
        migrations.CreateModel(
            name='WHTPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payment_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_payments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_payments_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_payments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WHT Payment',
                'verbose_name_plural': 'WHT Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
