# Generated by Django 6.0.6 on 2026-07-25 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('adjustment_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('adjustment_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_adjustments_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_adjustments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Adjustment',
                'verbose_name_plural': 'Cash Adjustments',
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashManagementFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cash_lost', models.DecimalField(decimal_places=4, default=0, help_text='Total cash ever recorded as lost, all-time (gross, only ever increases).', max_digits=20)),
                ('total_cash_recovered', models.DecimalField(decimal_places=4, default=0, help_text='Total cash ever recorded as found/recovered, all-time (gross, only ever increases).', max_digits=20)),
                ('net_cash_lost', models.DecimalField(decimal_places=4, default=0, help_text='total_cash_lost - total_cash_recovered, floored at 0. Stored, recalculated on every sync.', max_digits=20)),
                ('total_investor_capital', models.DecimalField(decimal_places=4, default=0, help_text='Total ever invested by all investors, all-time (gross, only ever increases).', max_digits=20)),
                ('total_investor_withdrawn', models.DecimalField(decimal_places=4, default=0, help_text='Total ever withdrawn by all investors, all-time (gross, only ever increases).', max_digits=20)),
                ('net_investor_capital', models.DecimalField(decimal_places=4, default=0, help_text='total_investor_capital - total_investor_withdrawn. Current total equity capital in the business. Stored, recalculated on every sync.', max_digits=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_management_flow_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Management Flow',
                'verbose_name_plural': 'Cash Management Flow',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('note', models.TextField(blank=True, default='')),
                ('total_invested', models.DecimalField(decimal_places=4, default=0, help_text='Total ever invested by this investor (gross, only ever increases).', max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=4, default=0, help_text='Total ever withdrawn by this investor (gross, only ever increases).', max_digits=20)),
                ('net_stake', models.DecimalField(decimal_places=4, default=0, help_text='total_invested - total_withdrawn. What this investor currently has in the business.', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('transaction_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_transactions_deleted', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cash_management.investor')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_transactions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Transaction',
                'verbose_name_plural': 'Investor Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
