# Generated by Django 6.0.6 on 2026-07-25 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmanagementflow',
            name='net_owner_capital',
            field=models.DecimalField(decimal_places=4, default=0, help_text="total_owner_contributions - total_owner_drawings. NOT floored at 0 — a sole owner can draw out more than they've deposited, financed by the business's profits, same as any real owner's drawing account.", max_digits=20),
        ),
        migrations.AddField(
            model_name='cashmanagementflow',
            name='total_owner_contributions',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total cash the owner has deposited into the business, all-time (gross, only ever increases).', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashmanagementflow',
            name='total_owner_drawings',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total cash the owner has withdrawn for personal use, all-time (gross, only ever increases).', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashmanagementflow',
            name='total_owner_withdrawals_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of owner drawing transactions, all-time (only ever increases).'),
        ),
        migrations.CreateModel(
            name='OwnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('contribution', 'Contribution'), ('drawing', 'Drawing')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('transaction_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_transactions_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_transactions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Transaction',
                'verbose_name_plural': 'Owner Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
