# Generated by Django 6.0.6 on 2026-07-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0002_cashmanagementflow_net_owner_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmanagementflow',
            name='total_owner_contributions_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of owner contribution transactions, all-time (only ever increases).'),
        ),
    ]
