# Generated by Django 6.0.6 on 2026-07-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0003_cashmanagementflow_total_owner_contributions_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmanagementflow',
            name='total_investor_net_worth',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Sum of every investor's current_worth (theoretical, growth-compounded value). Informational only — never used for withdrawal validation.", max_digits=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='current_worth',
            field=models.DecimalField(decimal_places=4, default=0, help_text='net_stake compounded monthly by growth_rate — a theoretical value, informational only, never used for withdrawal validation. Forced to exactly 0 when net_stake reaches 0 (full exit).', max_digits=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='growth_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Annual compound growth rate (e.g. 0.02 for 2%), zero or positive only. Editable any time — only affects entries posted after the change.', max_digits=5),
        ),
        migrations.AddField(
            model_name='investortransaction',
            name='worth_delta',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Exact change applied to current_worth by this transaction — stored so deletion can reverse it precisely.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='investor',
            name='net_stake',
            field=models.DecimalField(decimal_places=4, default=0, help_text='total_invested - total_withdrawn. What this investor currently has in the business. The ONLY figure withdrawals are validated against.', max_digits=20),
        ),
        migrations.CreateModel(
            name='InvestorValuationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM this entry applies to.', max_length=7)),
                ('rate_applied', models.DecimalField(decimal_places=4, help_text='Annual growth rate used for this entry.', max_digits=5)),
                ('worth_before', models.DecimalField(decimal_places=4, max_digits=20)),
                ('worth_after', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, help_text='worth_after - worth_before. Zero or positive — growth only, per the confirmed design.', max_digits=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_valuation_entries_created', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_entries', to='cash_management.investor')),
            ],
            options={
                'verbose_name': 'Investor Valuation Entry',
                'verbose_name_plural': 'Investor Valuation Entries',
                'ordering': ['-period', '-created_at'],
                'indexes': [models.Index(fields=['investor', '-period'], name='idx_investor_valuation_lookup')],
            },
        ),
    ]
