# Generated by Django 6.0.6 on 2026-07-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0004_cashmanagementflow_total_investor_net_worth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investortransaction',
            name='is_data_entry',
            field=models.BooleanField(default=False, help_text='True for pre-go-live investor capital recorded via the Data Entry app — does NOT move CashFlow.cash_in_hand (see data_entry.services).'),
        ),
    ]
