# Generated by Django 6.0.6 on 2026-08-03 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0005_investortransaction_is_data_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmanagementflow',
            name='growth_caught_up_through',
            field=models.CharField(blank=True, default='', help_text="YYYY-MM through which EVERY investor's growth is posted. Growth only becomes due at month boundaries, so while this equals the current month the per-investor catch-up loop can be skipped entirely (O(1) staleness check — same throttle pattern as users.TokenFlushState).", max_length=7),
        ),
        migrations.AddConstraint(
            model_name='investorvaluationentry',
            constraint=models.UniqueConstraint(fields=('investor', 'period'), name='uniq_investor_valuation_period'),
        ),
    ]
