# Generated by Django 6.0.6 on 2026-07-26 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_last_backup_at', models.DateTimeField(blank=True, help_text='Exact as_of timestamp the last successful LOCAL backup (full or incremental) covered up to.', null=True)),
                ('remote_last_backup_at', models.DateTimeField(blank=True, help_text='Exact as_of timestamp the last successful REMOTE backup (full or incremental) covered up to.', null=True)),
            ],
            options={
                'verbose_name': 'Backup Flow',
                'verbose_name_plural': 'Backup Flow',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], max_length=15)),
                ('destination', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('covers_from', models.DateTimeField(blank=True, null=True)),
                ('covers_to', models.DateTimeField()),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup History',
                'verbose_name_plural': 'Backup History',
                'ordering': ['-created_at'],
            },
        ),
    ]
