# Generated by Django 6.0.6 on 2026-07-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='schema_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
