# Generated by Django 6.0.6 on 2026-08-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_backuphistory_schema_migrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuphistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
