# Generated by Django 6.0.6 on 2026-07-25 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpenseMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7, unique=True)),
                ('total_assigned', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_paid', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_pending', models.DecimalField(decimal_places=4, default=0, help_text='total_assigned - total_paid, floored at 0. Stored, recalculated on every sync.', max_digits=20)),
                ('is_fully_paid', models.BooleanField(db_index=True, default=False, help_text='True exactly when total_pending reaches 0 and total_assigned > 0.')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurring Expense Monthly Stats',
                'verbose_name_plural': 'Recurring Expense Monthly Stats',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('start_date', models.DateField(help_text='First month this obligation is eligible to be assigned.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Expense',
                'verbose_name_plural': 'Recurring Expenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM this assignment is for.', max_length=7)),
                ('name_snapshot', models.CharField(max_length=255)),
                ('category_name_snapshot', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Assigned amount, frozen from the template at assignment time.', max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('recurring_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='recurring_expenses.recurringexpense')),
            ],
            options={
                'verbose_name': 'Recurring Expense Assignment',
                'verbose_name_plural': 'Recurring Expense Assignments',
                'ordering': ['-period', '-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseAssignmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payment_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='recurring_expenses.recurringexpenseassignment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_payments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_payments_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_payments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Expense Payment',
                'verbose_name_plural': 'Recurring Expense Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_categories_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_categories_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Expense Category',
                'verbose_name_plural': 'Recurring Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recurringexpenseassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='recurring_expenses.recurringexpensecategory'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='recurring_expenses.recurringexpensecategory'),
        ),
        migrations.CreateModel(
            name='RecurringExpenseFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assigned_amount', models.DecimalField(decimal_places=4, default=0, help_text='Sum of every RecurringExpenseAssignment.amount ever created, all-time. Only ever increases.', max_digits=20)),
                ('total_paid_amount', models.DecimalField(decimal_places=4, default=0, help_text='Sum of every non-deleted payment ever made, all-time.', max_digits=20)),
                ('total_pending_amount', models.DecimalField(decimal_places=4, default=0, help_text='total_assigned_amount - total_paid_amount, floored at 0. Stored, recalculated on every sync.', max_digits=20)),
                ('total_assignments_count', models.PositiveIntegerField(default=0)),
                ('total_active_templates', models.PositiveIntegerField(default=0, help_text='Count of active, non-deleted RecurringExpense templates.')),
                ('total_active_monthly_obligation', models.DecimalField(decimal_places=4, default=0, help_text='Sum of amount across active templates — what would be owed this month if everything were assigned.', max_digits=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_flow_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Expense Flow',
                'verbose_name_plural': 'Recurring Expense Flow',
            },
        ),
        migrations.AddIndex(
            model_name='recurringexpenseassignment',
            index=models.Index(fields=['period', 'category'], name='idx_rea_period_category'),
        ),
        migrations.AddConstraint(
            model_name='recurringexpenseassignment',
            constraint=models.UniqueConstraint(fields=('recurring_expense', 'period'), name='unique_recurring_expense_assignment_per_period'),
        ),
    ]
