# Generated by Django 6.0.6 on 2026-07-26 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringexpenseassignment',
            name='unique_recurring_expense_assignment_per_period',
        ),
        migrations.AddField(
            model_name='recurringexpenseassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringexpenseassignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_assignments_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringexpenseassignment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='recurringexpenseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('recurring_expense', 'period'), name='unique_recurring_expense_assignment_per_period'),
        ),
    ]
