# Generated by Django 6.0.6 on 2026-08-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_expenses', '0003_trigram_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpenseassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
