# Generated by Django 6.0.6 on 2026-07-26 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_management', '0004_cashmanagementflow_total_investor_net_worth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7, unique=True)),
                ('gross_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gross_cogs', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gross_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_cogs', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_gross_profit', models.DecimalField(decimal_places=4, default=0, help_text='net_revenue - net_cogs — the starting point for net_profit below.', max_digits=20)),
                ('expenses_paid', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('recurring_expenses_paid', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('gst_paid', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('wht_paid', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('lost_inventory_net', models.DecimalField(decimal_places=4, default=0, help_text='Lost this month minus found-as-of-finalization for those same items.', max_digits=20)),
                ('lost_cash_net', models.DecimalField(decimal_places=4, default=0, help_text='Cash lost this month minus cash found this month (both dated events).', max_digits=20)),
                ('depreciation', models.DecimalField(decimal_places=4, default=0, help_text='Sum of AssetValuationEntry depreciation posted for this period.', max_digits=20)),
                ('disposal_gain_loss', models.DecimalField(decimal_places=4, default=0, help_text='Signed — positive for a net gain on asset disposals this month, negative for a net loss. Added, not subtracted.', max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=4, default=0, help_text="The 'real profit' for this month — net_gross_profit minus every deduction above, plus disposal_gain_loss.", max_digits=20)),
                ('total_investor_share_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_investor_share_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('owner_share_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('owner_share_amount', models.DecimalField(decimal_places=4, default=0, help_text='Informational only — the owner never gets a settle-share flow.', max_digits=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monthly Profit',
                'verbose_name_plural': 'Monthly Profits',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProfitInvestorShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name_snapshot', models.CharField(max_length=255)),
                ('share_percent_snapshot', models.DecimalField(decimal_places=4, help_text="This investor's ownership %% as of this month — frozen forever.", max_digits=10)),
                ('share_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount_paid_out', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount_reinvested', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_profit_shares', to='cash_management.investor')),
                ('monthly_profit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_shares', to='profits.monthlyprofit')),
            ],
            options={
                'verbose_name': 'Monthly Profit Investor Share',
                'verbose_name_plural': 'Monthly Profit Investor Shares',
                'ordering': ['monthly_profit', 'investor_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='InvestorProfitPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payout_date', models.DateField(db_index=True)),
                ('action_type', models.CharField(choices=[('payout', 'Payout'), ('reinvest', 'Reinvest')], max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_profit_payouts_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_profit_payouts_deleted', to=settings.AUTH_USER_MODEL)),
                ('linked_investor_transaction', models.ForeignKey(blank=True, help_text="Set only when action_type='reinvest' — the InvestorTransaction that brought the cash back in.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_profit_payout', to='cash_management.investortransaction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_profit_payouts_updated', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='profits.monthlyprofitinvestorshare')),
            ],
            options={
                'verbose_name': 'Investor Profit Payout',
                'verbose_name_plural': 'Investor Profit Payouts',
                'ordering': ['-payout_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_net_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_investor_profit_share', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_owner_profit_share', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_paid_out_to_investors', models.DecimalField(decimal_places=4, default=0, help_text='All-time, gross, only ever increases.', max_digits=20)),
                ('total_reinvested_by_investors', models.DecimalField(decimal_places=4, default=0, help_text='All-time, gross, only ever increases.', max_digits=20)),
                ('months_finalized_count', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_flow_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profit Flow',
                'verbose_name_plural': 'Profit Flow',
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyprofitinvestorshare',
            constraint=models.UniqueConstraint(fields=('monthly_profit', 'investor'), name='unique_investor_share_per_month'),
        ),
    ]
