# Generated by Django 6.0.6 on 2026-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitflow',
            name='total_gross_profit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Sum of gross_profit across every FINALIZED month only — excludes the current, still-open month.', max_digits=20),
        ),
        migrations.AddField(
            model_name='profitflow',
            name='total_net_gross_profit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Sum of net_gross_profit (after returns) across every finalized month.', max_digits=20),
        ),
    ]
