# Generated by Django 6.0.6 on 2026-07-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0002_profitflow_total_gross_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyprofit',
            name='lost_cash_net',
        ),
        migrations.RemoveField(
            model_name='monthlyprofit',
            name='lost_inventory_net',
        ),
        migrations.AddField(
            model_name='monthlyprofit',
            name='found_cash',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cash marked found this month (CashAdjustment FOUND events dated this month) — added to profit.', max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlyprofit',
            name='found_inventory',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Value of inventory recovered this month (LostInventoryRecovery dated this month, regardless of when originally lost) — added to profit.', max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlyprofit',
            name='lost_cash',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cash marked lost this month (CashAdjustment LOST events dated this month).', max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlyprofit',
            name='lost_inventory',
            field=models.DecimalField(decimal_places=4, default=0, help_text='FIFO cost of inventory lost this month (LostInventoryRecord created this month).', max_digits=20),
        ),
    ]
