# Generated by Django 6.0.6 on 2026-08-02 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0005_investortransaction_is_data_entry'),
        ('profits', '0003_remove_monthlyprofit_lost_cash_net_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profitflow',
            name='total_paid_out_to_owner',
            field=models.DecimalField(decimal_places=4, default=0, help_text='All-time, gross, only ever increases.', max_digits=20),
        ),
        migrations.AddField(
            model_name='profitflow',
            name='total_reinvested_by_owner',
            field=models.DecimalField(decimal_places=4, default=0, help_text='All-time, gross, only ever increases.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='monthlyprofit',
            name='owner_share_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The exact remainder: net_profit - total_investor_share_amount. Settled the same way as an investor share — see MonthlyProfitOwnerShare.', max_digits=20),
        ),
        migrations.CreateModel(
            name='MonthlyProfitOwnerShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount_paid_out', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount_reinvested', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10)),
                ('monthly_profit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_share', to='profits.monthlyprofit')),
            ],
            options={
                'verbose_name': 'Monthly Profit Owner Share',
                'verbose_name_plural': 'Monthly Profit Owner Shares',
                'ordering': ['-monthly_profit__period'],
            },
        ),
        migrations.CreateModel(
            name='OwnerProfitPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payout_date', models.DateField(db_index=True)),
                ('action_type', models.CharField(choices=[('payout', 'Payout'), ('reinvest', 'Reinvest')], max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profit_payouts_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profit_payouts_deleted', to=settings.AUTH_USER_MODEL)),
                ('linked_owner_transaction', models.ForeignKey(blank=True, help_text="Set only when action_type='reinvest' — the OwnerTransaction that brought the cash back in.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_profit_payout', to='cash_management.ownertransaction')),
                ('owner_share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='profits.monthlyprofitownershare')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profit_payouts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Profit Payout',
                'verbose_name_plural': 'Owner Profit Payouts',
                'ordering': ['-payout_date', '-created_at'],
            },
        ),
    ]
