# Generated by Django 6.0.6 on 2026-08-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_trigram_search_indexes'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpricedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unpriced_entry', to='purchases.product')),
            ],
            options={
                'verbose_name': 'Unpriced Product',
                'verbose_name_plural': 'Unpriced Products',
                'ordering': ['product__name'],
            },
        ),
    ]
