# Generated by Django 6.0.6 on 2026-08-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0007_invoice_payment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue_caught_up_through', models.DateField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Score Flow',
                'verbose_name_plural': 'Credit Score Flow',
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=50)),
                ('tier', models.CharField(choices=[('good', 'Good (70+)'), ('average', 'Average (31-69)'), ('poor', 'Poor (<=30)')], db_index=True, default='average', max_length=10)),
                ('factor_breakdown', models.JSONField(blank=True, default=dict, help_text="Snapshot of each factor's contribution as of last_calculated_at.")),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_score', to='billing.customer')),
            ],
            options={
                'verbose_name': 'Customer Credit Score',
                'verbose_name_plural': 'Customer Credit Scores',
            },
        ),
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_after', models.PositiveSmallIntegerField()),
                ('tier_before', models.CharField(blank=True, choices=[('good', 'Good (70+)'), ('average', 'Average (31-69)'), ('poor', 'Poor (<=30)')], max_length=10, null=True)),
                ('tier_after', models.CharField(choices=[('good', 'Good (70+)'), ('average', 'Average (31-69)'), ('poor', 'Poor (<=30)')], max_length=10)),
                ('trigger', models.CharField(help_text='e.g. customer_created, invoice_confirmed, payment_received, payment_deleted, return_accepted, due_date_extended, overdue_catchup', max_length=30)),
                ('reference', models.CharField(blank=True, default='', max_length=50)),
                ('factor_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_score_history', to='billing.customer')),
            ],
            options={
                'verbose_name': 'Credit Score History',
                'verbose_name_plural': 'Credit Score History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='credit_scor_custome_77e408_idx')],
            },
        ),
    ]
