# Generated by Django 6.0.6 on 2026-07-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_lost_inventory_worth',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total FIFO cost of all products marked lost. Only ever increases — no reversal exists.', max_digits=20),
        ),
    ]
