# Generated by Django 6.0.6 on 2026-07-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0002_cashflow_total_lost_inventory_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_customer_returns_cogs',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total COGS reversed via accepted customer returns. Only ever increases.', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_customer_returns_value',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total value of accepted returns from customers. Only ever increases.', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_gross_profit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total gross profit across all confirmed invoices. Only ever increases.', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_invoice_cogs',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total COGS across all confirmed invoices. Only ever increases.', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_invoice_revenue',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total grand_total across all confirmed invoices (invoiced amount, not cash received). Only ever increases.', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_purchase_returns_value',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total value of accepted returns to suppliers. Only ever increases.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True),
        ),
    ]
