# Generated by Django 6.0.6 on 2026-07-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_cashflow_total_customer_returns_cogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_purchase_returns_cogs',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total pre-tax cost portion (total_return_gross) of accepted returns to suppliers — mirrors total_customer_returns_cogs for dashboard symmetry. Only ever increases.', max_digits=20),
        ),
    ]
