# Generated by Django 6.0.6 on 2026-07-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0004_cashflow_total_purchase_returns_cogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_lost_inventory_recovered',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total FIFO cost of lost products later marked found (gross, only ever increases). Dashboard shows worth minus this as the net figure.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='total_lost_inventory_worth',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total FIFO cost of all products ever marked lost (gross, only ever increases).', max_digits=20),
        ),
    ]
