# Generated by Django 6.0.6 on 2026-07-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0005_cashflow_total_lost_inventory_recovered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_recurring_expenses_paid',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total ever paid against recurring expense assignments (salaries, rent, ...), all-time. Only ever increases; only moves on payment, never on assignment.', max_digits=20),
        ),
    ]
