# Generated by Django 6.0.6 on 2026-07-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0006_cashflow_total_recurring_expenses_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_cash_inflow',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Sum of every currently-active cash inflow event (same set as get_cash_in_hand_breakdown()'s inflow rows). Decreases on delete/reversal of an inflow — NOT gross-ever. total_cash_inflow - total_cash_outflow always equals cash_in_hand.", max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_cash_outflow',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Sum of every currently-active cash outflow event (same set as get_cash_in_hand_breakdown()'s outflow rows). Decreases on delete/reversal of an outflow — NOT gross-ever.", max_digits=20),
        ),
    ]
