# Generated by Django 6.0.6 on 2026-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0007_cashflow_total_cash_inflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('movement_type', models.CharField(max_length=40)),
                ('date', models.DateField(help_text='Business date shown in the drawer (payment/expense/... date).')),
                ('occurred_at', models.DateTimeField(help_text="Source row's created_at — the drawer's sort key.")),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=100)),
                ('method', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('source_model', models.CharField(help_text='app_label.model_name of the row that caused this event.', max_length=60)),
                ('source_id', models.BigIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cash Movement',
                'verbose_name_plural': 'Cash Movements',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['is_deleted', '-occurred_at'], name='idx_cashmove_active_occurred'), models.Index(fields=['is_deleted', 'direction', '-occurred_at'], name='idx_cashmove_dir_occurred'), models.Index(fields=['date'], name='idx_cashmove_date')],
                'constraints': [models.UniqueConstraint(fields=('source_model', 'source_id'), name='uniq_cashmove_source')],
            },
        ),
    ]
