# Generated by Django 6.0.6 on 2026-08-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0009_trigram_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_expenses_count',
            field=models.IntegerField(default=0, help_text='Non-deleted expenses. +1 on create_expense, -1 on delete_expense.'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_invoices_count',
            field=models.IntegerField(default=0, help_text='Confirmed, non-data-entry invoices. +1 in sync_invoice_confirmed; confirmed invoices are undeletable, so it never decrements.'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_purchases_count',
            field=models.IntegerField(default=0, help_text='Confirmed, non-data-entry purchase orders. +1 in sync_purchase_order_confirmed; confirmed orders are undeletable, so it never decrements.'),
        ),
    ]
