# Generated by Django 6.0.6 on 2026-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('return', 'Return'), ('advance', 'Advance Payment'), ('opening_balance', 'Opening Balance')], db_index=True, max_length=20),
        ),
    ]
