# Generated by Django 6.0.6 on 2026-08-05 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_trigram_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierledger',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_supplier_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierledger',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
