# Generated by Django 6.0.6 on 2026-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFlushState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_flushed_at', models.DateTimeField(blank=True, help_text='When expired tokens were last flushed. Null = never flushed.', null=True)),
            ],
            options={
                'verbose_name': 'Token Flush State',
                'verbose_name_plural': 'Token Flush State',
            },
        ),
    ]
